config/routes.rb
Rails.application.routes.draw do
  devise_for:users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources:groups do
    resources:posts
  end
  root 'groups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many:posts
  validates:title,presence:true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to:user
  belongs_to:group
  validates:content,presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many:groups
  has_many:posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  #在only中的action执行的最开始执行before_action后面的方法：
  before_action:authenticate_user!,only:[:edit,:update,:new,:create,:destroy]
  before_action :find_group_and_check_permission, only: [:edit, :update, :destroy]

#group列表页
#=SELECT "groups".* FROM "groups"
  def index
    @groups=Group.all
  end
  #显示某一个group详情（根据id值，其包含在url中）
  #=SELECT  "groups".* FROM "groups" WHERE "groups"."id" = ?
  def show
    @group=Group.find(params[:id])
  end
  #new和create方法成对定义：
  def new
    #new方法只是在内存中创建一个group对象，未存入数据库
    @group=Group.new
  end
  def create
    #如：@group=Group.new(:title=>"111",:description=>"222")
    @group=Group.new(group_params)
    #插入数据库的数据必须要有user_id属性
    @group.user=current_user
    #执行save，才把刚new的数据插入数据库。@group此时=插入的那一条数据（对象）
    #=INSERT INTO "groups" ("title", "description", "created_at", "updated_at", "user_id") VALUES (?, ?, ?, ?, ?)  [["title", "111"], ["description", "222"], ["created_at", "2020-01-22 16:22:38.303712"], ["updated_at", "2020-01-22 16:22:38.303712"], ["user_id", 1]]
    if @group.save
      #如果插入成功，返回列表页
      redirect_to groups_path,notice:"create success"
    else
      #继续留在新增页：
      render:new
    end
  end
#edit和update方法成对定义：
  def edit
  end
  def update
    #update需要有title和description字段值,作为参数，在最后定义了。
    #如果更新(编辑)成功，返回列表页
    if @group.update(group_params)
      redirect_to groups_path,notice:"update success"
    else
      #继续留在编辑页：
      render:edit
    end
  end


  def destroy
    #删除某一条指定数据（根据id）
    #=DELETE FROM "groups" WHERE "groups"."id" = ?  [["id", 15]]
    @group.destroy
    #不能用notice，notice都是绿色的：
    flash[:alert]="delete success"
    redirect_to groups_path
  end

  private
  def find_group_and_check_permission
    #
    @group=Group.find(params[:id])
    if current_user!=@group.user
      redirect_to root_path,alert:"你没有权限"
    end
  end
  def group_params
    params.require(:group).permit(:title,:description)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]


#show\new等这些action大部分都要操作数据库，相当于执行select\insert等命令。里面的代码可直接在rails console中执行的。
  def show
    #先找到当前访问的这个group（根据id，其在url中有）
    @group=Group.find(params[:id])
    #然后把获取其下面所有posts. group和post关联关系在models下面的xx.rb几个文件中定义，has_many或belongs_to
    #这个posts变量，直接在show.html.erb中用不了
    @posts=@group.posts
  end

  #new只是在内存中创建对象，不操作数据库
  def new
    @group=Group.find(params[:group_id])
    @post=Post.new
  end
  #create=new+save(执行sql操作数据库，所以对应表中的字段都有赋值)
  def create
    @group=Group.find(params[:group_id])
    #新建一个具体的post对象
    @post=Post.new(post_params)
    @post.group=@group
    @post.user=current_user
    #如果保存到数据库成功
    if @post.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.erb
<%# 注释：“@”后面必须是对应数据模型的model名，｜f｜可以是任何字母，只要下面dom中的和其一致—— %>
<%= simple_form_for @group do|f| %>

  <div class="form-group">
  <%# 该input的id为:group_title。title是表中字段—— %>
    <%= f.input :title,input_html:{class:'form-control'}%>
    <%# 该input的id为:group_description %>
    <%= f.input :description,input_html:{class:'form-control'}%>
  </div>
  <%= f.submit "提交",class:'btn btn-primary',data:{disable_with:'submiting...'}%>

<% end %>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>编辑讨论版</h2>
  <hr>
  <%=render "form"%>

</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <h2>Rails101</h2>
  <div class="group">
    <%= link_to('新增版块',new_group_path,class:"btn btn-primary") %>
  </div>
  <br>

  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <!-- <td>#</td> -->
        <td>版块名称</td>
        <td>描述</td>
        <td>创建人</td>
        <td>操作</td>

      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
      <tr>
        <!-- <td>#</td> -->
        <!-- group_path对应controller中“show”这个action来处理： -->
        <td><%= link_to(group.title,group_path(group)) %></td>
        <td><%= group.description %></td>
        <td><%= group.user.email%></td>
        <td>
          <% if current_user && current_user==group.user%>
          <%# 对应edit这个action—— %>
          <%= link_to("编辑",edit_group_path(group),class:"btn btn-default") %>
          <%= link_to("删除",group_path(group),method: :delete,data:{confirm:"are you sure?"},class:"btn btn-default") %>
          <%end%>
        </td>
      </tr>
      <% end %>
    </tbody>




  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>新增讨论版</h2>
  <hr>
  <%=render "form"%>

</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <!-- 这里面的@group是具体的那一个 -->
  <h2><%=@group.title%></h2>
  <p><%=@group.description%></p>

  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>文章内容</th>
        <th>发布人</th>
        <th>发布时间</th>
      </tr>
    </thead>
    <tbody>
      <!-- #这里按照教程上的直接posts.each会报错 -->
      <!-- 意思是循环针对当前group下posts中的每一个，do 里面的动作（这里就是在列表中显示其几个字段值） -->
      <% @group.posts.each do |post| %>
      <tr>
        <td>
          <%=post.content%>
        </td>
        <td>
          <%=post.user.email%>
        </td>
        <td>
          <%=post.created_at%>
        </td>
      </tr>
      <%end%>
    </tbody>
  </table>

  <div class="col-md-1">
    <%if current_user %>
    <%# #对应访问controller中的new action,对应的url无需配置，按约定生成—— %>
      <%=link_to("发布文章",new_group_post_path(@group),class:"btn btn-primary")%>
    <%end%>
  </div>
  <div class="col-md-1">
    <%if current_user&&current_user==@group.user %>
    <%# #对应访问controller中的edit action,对应的url无需配置，按约定生成—— %>
    	<%=link_to("编辑版块",edit_group_path(@group),class:"btn btn-default")%>
    <%end%>
  </div>
  <div class="col-md-1">
    <%=link_to("返回",groups_path,class:"btn btn-default")%>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails101</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<h2 class="text-center">新增文章</h2>
<div class="col-md-4 col-md-offset-4">
  
  <%=simple_form_for [@group,@post] do |f|  %>
    <div class="form-group">
      <%=f.input :content,input_html:{class:"form-control"}%>
    </div>
    <div class="form-actions">
      <%=f.submit "提交",class:"btn btn-primary",disable_with:"submiting...."%>
    </div>
  <%end%>
</div>